---
title: "All Dimensions"
format: 
  html:
    self-contained: true
    toc: true
    toc-depth: 6
    smooth-scroll: true
editor: source

execute:
  echo: false
  warning: false
---

```{r}
library(knitr); library(plyr);  library(dplyr); library(ggplot2); library(gridExtra); library(tidyr); 
library (reshape); 
library(tidyverse)  # para fct_rev
library (ggpubr) # para multi_figuras
library(scales)  # Para usar la función percent
```

```{r}
load("~/Dropbox/_LATINOS/DATA_latinos/2_DFrames/D1p.LATIN_plus.RData")

# LATINUS-FULL
LL_FULL <- D1p.LATIN_plus    ; rm(D1p.LATIN_plus)

# LATINUS-DEMO - since last transition
LL <-LL_FULL [-which ((LL_FULL$country_ch=="Argentina" & (LL_FULL$gov <41 |LL_FULL$gov ==45)) | (LL_FULL$country_ch=="Uruguay" & LL_FULL$gov <42)) ,   ]


# PAIS  SELECTION   + port_typeCOUNTRY 
PP <-LL[which (LL$country_ch=="Portugal"   ),]

```

```{r}
PP$expertise_Job <- PP$expertise_Prof
#table (PP$expertise_Job_type)
```


```{r}
PP <- PP %>%
  mutate(coal_std = case_when(
    coal %in% c("non-coalition", "floor coalition") ~ "non-coalition",
    coal == "portfolio coalition" ~ "portfolio coalition",
    TRUE ~ NA_character_  # para valores no reconocidos
  ))

#table (PP$coal, PP$coal_std, exclude = F)
```

```{r}
# (ajuste truch)
# table (PP$edu_level)
PP$edu_levelBACK <- PP$edu_level

PP$edu_level[which(PP$edu_level=="military")] <- "graduate"

PP$edu_level <- factor (PP$edu_level)

# table (PP$edu_levelBACK, PP$edu_level, exclude = F)
```


```{r}
PP$port_typeCOUNTRY <- as.factor(PP$port_typeCOUNTRY)

PP$gov_ch.f.sinOrdenar <- as.factor(PP$gov_ch); 
PP$gov_ch.f  <- reorder(PP$gov_ch.f.sinOrdenar, PP$gov_begin)

hh <-  PP[which(PP$port_type=="HoG"),]
mm <-  PP[which(PP$minister=="ministers"),]
ii <- mm[which(mm$min_inaug=="inaugural"),]

incum_M   <-  PP[which(PP$min_incum=="incumbent"),]
incum_m <-  mm[which(mm$min_incum=="incumbent"),]

actual <- mm[which(mm$gov==max(mm$gov)),]

hh$durat.y <- hh$durat/365
```

<br>
























***************************

# MANAGERIAL DIMENSION {#managerial}

## Section 2: Our Measures   

### Fig.2.1: Types  

```{r}
ggplot(PP,  aes(x=expertise_Manag_type, fill= expertise_Manag_type)) +
  geom_bar() + 
scale_fill_manual(values=c("white", "darkviolet","plum", "black")) +  
  guides(fill=guide_legend(title=NULL)) +   
  labs(x = NULL, y = NULL) +
    theme(axis.text.x = element_text(angle=30, hjust=1, vjust=1))+
  theme(legend.position="top") +
  coord_flip()
```
<br>

### Fig.2.2: Levels (with types integrated)     
```{r}
ggplot(PP,  aes(x=expertise_Manag, fill= expertise_Manag_type)) +
  geom_bar() + 
scale_fill_manual(values=c("white", "darkviolet","plum","black")) +  
  guides(fill=guide_legend(title=NULL)) +   
  labs(x = NULL, y = NULL) +
    theme(axis.text.x = element_text(angle=30, hjust=1, vjust=1))+
  theme(legend.position="top") +
  coord_flip()
```
<br>


## Sec3: Analyzing

### a) By time    
```{r}
ii_summarized <- ii %>%
  count(gov_ch.f, expertise_Manag)  %>%
  group_by(gov_ch.f) %>%          # 
  mutate(proportion = n / sum(n))  # Calcular la proporción de cada tipo de partisan

# Line graph with proportion y etiquetas sin decimales
ggplot(ii_summarized, aes(x = gov_ch.f, y = proportion, color = expertise_Manag, group = expertise_Manag)) +
  geom_line(size = 1) +   # Dibuja líneas conectando puntos
  geom_point(size = 2) +  # Agrega puntos en cada gobierno
  geom_text(aes(label = percent(proportion, accuracy = 1)), vjust = -0.5, size = 3) +  #  sin decimales
  scale_color_manual(values = c("white", "grey70", "purple")) +  
  guides(color = guide_legend(title = NULL)) +   
  labs(x = "Government", y = "Proportion of Ministers") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1)) +
  theme(legend.position = "top")
```
<br> 
<br> 

### By Portfolios' Field     
```{r}
# table (ii$expertise_Manag, ii$port_field_AggA, exclude = F)
       
ggplot(ii, aes(x = port_field_AggA, fill = expertise_Manag)) +
  geom_bar(position = "fill") +
scale_fill_manual(values = c("white" , "grey90", "purple")) +  

  labs(x = NULL, y = "Proporção", 
       fill = NULL,
       title = NULL) +
  coord_flip() 
```


### By gender
```{r}
# table (ii$expertise_Manag, ii$woman, exclude = F)
       
ggplot(ii, aes(x = woman, fill = expertise_Manag)) +
  geom_bar(position = "fill") +
scale_fill_manual(values = c("white" , "grey90", "purple")) +  

  labs(x = NULL, y = "Proporção", 
       fill = NULL,
       title = NULL) +
  coord_flip() 
```


### By Political Party     
```{r}
# table (ii$expertise_Manag, ii$partyMin, exclude = F)
       
ggplot(ii, aes(x = partyMin, fill = expertise_Manag)) +
  geom_bar(position = "fill") +
scale_fill_manual(values = c("white" , "grey90", "purple")) +  

  labs(x = NULL, y = "Proporção", 
       fill = NULL,
       title = NULL) +
  coord_flip() 
```


### By Core Portfolios
```{r}
# table (ii$expertise_Manag, ii$port_core, exclude = F)
       
ggplot(ii, aes(x = port_core, fill = expertise_Manag)) +
  geom_bar(position = "fill") +
scale_fill_manual(values = c("white" , "grey90", "purple")) +  

  labs(x = NULL, y = "Proporção", 
       fill = NULL,
       title = NULL) +
  coord_flip() 
```


### By Legislative Status     
```{r}
# table (ii$expertise_Manag, ii$legLow_gov, exclude = F)
       
ggplot(ii, aes(x = legLow_gov, fill = expertise_Manag)) +
  geom_bar(position = "fill") +
scale_fill_manual(values = c("white" , "grey90", "purple")) +  

  labs(x = NULL, y = "Proporção", 
       fill = NULL,
       title = NULL) +
  coord_flip() 
```


### By Coalition Status     
```{r}
# table (ii$expertise_Manag, ii$coal_std, exclude = F)
       
ggplot(ii, aes(x = coal_std, fill = expertise_Manag)) +
  geom_bar(position = "fill") +
scale_fill_manual(values = c("white" , "grey90", "purple")) +  

  labs(x = NULL, y = "Proporção", 
       fill = NULL,
       title = NULL) +
  coord_flip() 
```


